name: CI/CD
on:
  pull_request: {}
jobs:
  quality:
    name: Quality (python-${{ matrix.python-version }})
    runs-on: "ubuntu-latest"
    env:
      POETRY_VERSION: "1.8.3"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Synchronize repository
        uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
        shell: bash
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Format
        run: poetry run black scripts
      - name: Lint
        run: poetry run ruff check --force-exclude scripts
      - name: Typing
        run: poetry run mypy --ignore-missing-imports --scripts-are-modules scripts
